import type { Rule } from './shared.js';

// Intentionally high-signal patterns. This should be explainable and low-noise.
export const RULES: Rule[] = [
  {
    id: 'curl_pipe_sh',
    dimension: 'remote_exec',
    type: 'download-and-run',
    points: 70,
    severity: 'high',
    regex: /\bcurl\b[^\n|]{0,200}\|\s*(?:bash|sh|zsh)\b/gi,
    reason: 'Downloads content and pipes it directly into a shell.',
  },
  {
    id: 'wget_pipe_sh',
    dimension: 'remote_exec',
    type: 'download-and-run',
    points: 70,
    severity: 'high',
    regex: /\bwget\b[^\n|]{0,200}\|\s*(?:bash|sh|zsh)\b/gi,
    reason: 'Downloads content and pipes it directly into a shell.',
  },
  {
    id: 'powershell_iex',
    dimension: 'remote_exec',
    type: 'download-and-run',
    points: 70,
    severity: 'high',
    regex:
      /\b(?:iwr|invoke-webrequest|invoke-restmethod)\b[^\n]*\|\s*(?:iex|invoke-expression)\b/gi,
    reason: 'PowerShell download-and-execute pattern (IWR/IRM piped to IEX).',
  },
  {
    id: 'eval_exec',
    dimension: 'remote_exec',
    type: 'suspicious',
    points: 30,
    severity: 'medium',
    // Avoid false positives for common safe code patterns like JS RegExp#exec: `/.../.exec(str)`.
    // The scan logic further suppresses `.exec(` property calls specifically.
    regex: /(?:\beval\s*\(|\bFunction\s*\(|\bexec\s*\()/g,
    reason: 'Dynamic code execution (eval/exec/Function) is risky and often unnecessary.',
  },
  {
    id: 'base64_decode_exec',
    dimension: 'obfuscation',
    type: 'obfuscation',
    points: 60,
    severity: 'high',
    regex: /\bbase64\b[^\n|]{0,200}\|\s*(?:bash|sh|zsh|python|node)\b/gi,
    reason:
      'Decodes base64 and pipes it into an interpreter, which is a common obfuscation/execution pattern.',
  },
  {
    id: 'ssh_key_access',
    dimension: 'secret_access',
    type: 'secret-access',
    points: 60,
    severity: 'high',
    regex:
      /~\/\.ssh\/(?:id_rsa|id_ed25519|authorized_keys|known_hosts)|\/\.ssh\/(?:id_rsa|id_ed25519)/gi,
    reason: 'References SSH key material or SSH config paths.',
  },
  {
    id: 'aws_creds_access',
    dimension: 'secret_access',
    type: 'secret-access',
    points: 45,
    severity: 'high',
    regex: /~\/\.aws\/(?:credentials|config)|\/\.aws\/(?:credentials|config)/gi,
    reason: 'References AWS credential/config paths.',
  },
  {
    id: 'npmrc_access',
    dimension: 'secret_access',
    type: 'secret-access',
    points: 35,
    severity: 'medium',
    regex: /~\/\.npmrc|\/\.npmrc\b/gi,
    reason: 'References .npmrc which can contain auth tokens.',
  },
  {
    id: 'macos_keychain_access',
    dimension: 'secret_access',
    type: 'secret-access',
    points: 60,
    severity: 'high',
    regex:
      /\bsecurity\s+(?:find-generic-password|find-internet-password|dump-keychain|find-certificate)\b/gi,
    reason: 'Accesses macOS Keychain via the `security` CLI.',
  },
  {
    id: 'curl_upload_file',
    dimension: 'exfiltration',
    type: 'exfiltration',
    points: 55,
    severity: 'high',
    regex: /\bcurl\b[^\n]*\s(?:-F|--form|-T|--upload-file)\s/gi,
    reason: 'Uploads local data via curl (form upload or upload-file).',
  },
  {
    id: 'netcat',
    dimension: 'exfiltration',
    type: 'exfiltration',
    points: 55,
    severity: 'high',
    regex: /\bnc\s+-[elnvw]\b|\bnetcat\b/gi,
    reason: 'Uses netcat, which is commonly used for ad-hoc data exfiltration or reverse shells.',
  },
  {
    id: 'cron_persist',
    dimension: 'persistence',
    type: 'persistence',
    points: 45,
    severity: 'high',
    regex: /\bcrontab\b|\b\/etc\/cron\.(?:d|daily|weekly|monthly)\b/gi,
    reason: 'Modifies or references cron for persistence.',
  },
  {
    id: 'shell_profile_modify',
    dimension: 'persistence',
    type: 'persistence',
    points: 35,
    severity: 'medium',
    regex: /\b(?:\.bashrc|\.bash_profile|\.zshrc|\.profile)\b/gi,
    reason: 'References shell profile files, which can be used for persistence.',
  },
  {
    id: 'rm_rf',
    dimension: 'destructive',
    type: 'destructive',
    points: 50,
    severity: 'high',
    regex: /\brm\s+-rf\s+(?:\/|\$HOME|~|\.\.)(?:\s|$)/gi,
    reason: 'Broad `rm -rf` usage can be destructive.',
  },
  {
    id: 'download_executable_link',
    dimension: 'remote_exec',
    type: 'download-and-run',
    points: 65,
    severity: 'high',
    regex: /\bhttps?:\/\/[^\s)]+?\.(?:exe|msi|dmg|pkg|appimage)(?:[?#][^\s)]*)?/gi,
    reason: 'Links to a downloadable executable/installer. Treat with extreme caution.',
  },
  {
    id: 'download_archive_link',
    dimension: 'remote_exec',
    type: 'suspicious',
    points: 35,
    severity: 'medium',
    regex: /\bhttps?:\/\/[^\s)]+?\.(?:zip|rar|7z)(?:[?#][^\s)]*)?/gi,
    reason: 'Links to a downloadable archive. Archives are a common malware delivery mechanism.',
  },
  {
    id: 'ip_url',
    dimension: 'remote_exec',
    type: 'suspicious',
    points: 35,
    severity: 'medium',
    regex: /\bhttps?:\/\/(?:\d{1,3}\.){3}\d{1,3}(?::\d{1,5})?(?:\/[^\s)]*)?/gi,
    reason: 'Uses an IP-based URL. In this context, that is often suspicious.',
  },
  {
    id: 'password_protected_archive',
    dimension: 'obfuscation',
    type: 'obfuscation',
    points: 50,
    severity: 'high',
    regex:
      /\b(?:password|passcode|pw)\b[^\n]{0,120}\b(?:zip|rar|7z|archive)\b|\b(?:zip|rar|7z|archive)\b[^\n]{0,120}\b(?:password|passcode|pw)\b/gi,
    reason:
      'Mentions a password alongside an archive. Password-protected archives are commonly used to evade scanning.',
  },
  {
    id: 'run_executable_instruction',
    dimension: 'remote_exec',
    type: 'download-and-run',
    points: 60,
    severity: 'high',
    regex:
      /\b(?:run|execute|open|double-?click|launch|start)\b[^\n]{0,120}\b[^\s)]+\.(?:exe|msi|bat|cmd|ps1|dmg|pkg|appimage)\b/gi,
    reason: 'Instructs the user to run a downloaded executable or script file.',
  },
];
